### ISSUE TITLE
Iterative verifier multiple reverification before cutover

### ISSUE THREAD

**Issue by shuhaowu** [Shopify/ghostferry#13]
We can tie in the metrics of how many rows we are verifying vs the amount of binlogs we are streaming to figure out how many times we should reverify before we go to cutover. With some sort of basic controls algorithm we could potentially reduce the downtime due to verification to essentially 0.

If we implement this we need to be able to configure maximum number of reverification.

**Comment by hkdsun** [comment]
Can this be closed by https://github.com/Shopify/ghostferry/pull/36?

**Comment by shuhaowu** [comment]
Yes.
