### ISSUE TITLE
UI incomplete render

### ISSUE THREAD

**Issue by nethalo** [Shopify/ghostferry#188]
while accessing the UI, the content is incomplete and it throws this error: template: index.html:82:24: executing "index.html" at : error calling eq: invalid type for comparison

<img width="1048" alt="Screen Shot 2020-06-01 at 10 30 40" src="https://user-images.githubusercontent.com/7537643/83425338-2d437f00-a3f3-11ea-81fa-aeaa31bede3b.png">

**Comment by tiwilliam** [comment]
Thanks for the report, this is now fixed in master.
