### ISSUE TITLE
Ghostferry Idempotence

### ISSUE THREAD

**Issue by fjordan** [Shopify/ghostferry#200]
While there is some form of implicit assurance (in the form of `INSERT IGNORE` and the added predicates for all generated SQL DMLs) that Ghostferry is idempotent in nature, there is no explicit or formal validation either in tests or the the TLA+ specification. 

Explicitly verifying this feature of Ghostferry's algorithm is something that should be pursued as it would allow users of Ghostferry to replay moves from positions in the TableIterator and/or BinlogWriter that may have previously been applied. 

For example, if a run completes to position _p2_ and is then interrupted, but it then resumed from point _p1_, or even _p0_, it must be proven that re-running ghostferry from these previous positions will not corrupt any data and that source/target equality will be successfully achieved. 

![image](https://user-images.githubusercontent.com/390811/88227683-8f6e7280-cc33-11ea-86d3-e2dfea204c65.png)

Following this verification, it may be very helpful in the case that hundreds, or thousands, or more Ghostferry processes are taking place and would like to support interruption. Instead of requiring each of these moves to capture their state at this exact point-in-time at interrupt, we could then periodically persist the state of the ghostferry run to be resumed in the event of interruption and bypass a potential thundering herd of writes.

/cc @Shopify/pods

**Comment by milanatshopify** [comment]
Being able to periodically save the (future resume) state would also simplify dealing with different interrupt scenarios, as well as cover the "the k8s pod just died" situations we frequently encounter.

**Comment by fjordan** [comment]
Closed by https://github.com/Shopify/ghostferry/pull/207
