### ISSUE TITLE
Found mistakes in tutorial docs

### ISSUE THREAD

**Issue by shlomi-noach** [Shopify/ghostferry#25]
Please see https://github.com/Shopify/ghostferry/pull/24 for fixes.

```
GRANT SELECT, REPLICATION SLAVE, REPLICATION CLIENT ON `abc`.* TO 'ghostferry'@'%';
```
is an invalid query (you cannot grant `REPLICATION SLAVE, REPLICATION CLIENT` on a schema)

The `SELECT * FROM abc.table1 WHERE id = 351;` validation query needs to run on the target DB, not the source DB.

**Comment by shuhaowu** [comment]
Fixed by #24
