### ISSUE TITLE
ControlServer ETA is negative after "Done"

### ISSUE THREAD

**Issue by shuhaowu** [Shopify/ghostferry#251]
It seems like the ETA in the ControlServer UI continues to calculate after the Done state, which results in a negative ETA value. This should be fixed.

![image](https://user-images.githubusercontent.com/338100/107240265-bb96e880-69f7-11eb-9446-2a9078e6d65f.png)

**Comment by lstp** [comment]
@shuhaowu I wasn't able to replicate this locally. Do you mind adding steps to replicate the issue. I see ETA as 0 when I run a test locally. 


![Screen Shot 2021-02-09 at 1 23 55 PM](https://user-images.githubusercontent.com/4635189/107419288-9c768480-6ae5-11eb-8d54-9f2bfc4f4b5e.png)

**Comment by tiwilliam** [comment]
This could be due to `targetPaginationKeys` being empty or almost empty if resuming a run. That would cause `totalPaginationKeysToCopy` to be smaller than `completedPaginationKeys` and generate a negative number.

**Comment by lstp** [comment]
resolved in https://github.com/Shopify/ghostferry/pull/256
