### ISSUE TITLE
Check and disallow foreign key during the beginning of the run

### ISSUE THREAD

**Issue by shuhaowu** [Shopify/ghostferry#3]
Foreign key is not supported (same as ghost). We should ensure ghostferry bails on start up when it detects a FK on a table as oppose to crashing in the middle of a run.

**Comment by paarthmadan** [comment]
@shuhaowu Is this issue still relevant? If that's the case, I can take it on!

**Comment by shuhaowu** [comment]
It is still relevant. That said, if we do this, we need to do the following:

1. By default, Ghostferry should fail when a FK is detected.
2. If an override flag is specified in the configuration, the Ghostferry will _not_ fail if a FK is detected. See #166.
