### ISSUE TITLE
Ensure Prepared Statements are Used Where Necessary

### ISSUE THREAD

**Issue by fjordan** [Shopify/ghostferry#52]
To ensure MySQL's plain text interface isn't used, we need to make sure this uses prepared statements. A test should be added that fails if non-prepared statements are used to query MySQL.

More context can be gathered from https://github.com/Shopify/ghostferry/pull/44#discussion_r201636009

**Comment by fw42** [comment]
Having a test that fails as soon as you write any kind of non-prepared statement seems a bit overkill to me. Why are non-prepared statements bad in general?

What I was getting at with my comment in https://github.com/Shopify/ghostferry/pull/44#discussion_r201636009 is that this one particular query supposedly has a good reason why it's using a prepared statement (and that reason should be captured by a test). But I imagine the test itself doesn't need to know anything about prepared vs. non-prepared statements (that's an implementation detail, the same bug could probably be solved in some other way), i.e. [test the interface, not the implementation](http://www.richardlord.net/blog/tdd/test-the-interface-not-the-implementation.html).

**Comment by fjordan** [comment]
Go's MySQL driver has two protocols: 1. Plain text and 2. Binary. The binary protocol is only used with prepared statements, and allows us to know the actual type of the data being transmitted versus just being `[]uint8`s everywhere. 

As far as I can tell, in addition to the performance gain, we need to know the type of the data being transmitted. Are there places we shouldn't be using prepared statements? This project may warrant strictly enforcing that given its purpose, although we do query for things like `read_only` that obviously don't require type information.

**Comment by shuhaowu** [comment]
We use multistatements to execute binlog updates. Multistatement is only usable over the text interface and not the prepared interface.

**Comment by shuhaowu** [comment]
Is this still a problem?

**Comment by fjordan** [comment]
No, I don't think it's worth tracking as an issue right now.
