### ISSUE TITLE
should not check binlog_row_image variable if using low version mysql/mariadb?

### ISSUE THREAD

**Issue by tclh123** [Shopify/ghostferry#74]
`binlog_row_image` parameter introduced in mariadb 10.1.6.

https://mariadb.com/kb/en/library/replication-and-binary-log-system-variables/#binlog_row_image

**Comment by shuhaowu** [comment]
> The default value is full. In MySQL 5.5 and earlier, full row images are always used for both before images and after images. If you need to replicate from a MySQL 5.6 (or later) master to a slave running a previous version of MySQL, the master should always use this value. 

This should be a relatively straightforward fix in the code. I would like to see the check occur for only mysql version greater than 5.6.2.

**Comment by shuhaowu** [comment]
Also note, we don't have time to implement this feature. If you want to contribute code, I'll be able to review the PR.

**Comment by shuhaowu** [comment]
I assume this is no longer needed.
