### ISSUE TITLE
Tests hang on mysql2 connection and command out of sync

### ISSUE THREAD

**Issue by shuhaowu** [Shopify/ghostferry#91]
The datawriter was causing some flakiness in tests (and almost certainty on travis) where:

1. It would hang on DataWriter#write_data, causing the DataWriter thread to stall indefinitely and the tests will hang forever.
2. Commands out of sync exception that immediately fail the tests.

This was worked around via https://github.com/Shopify/ghostferry/commit/56a3100b12ecf7c09f4fc7a4fbda93325d147efb as I don't have too much time to look into it atm.

The first problem resembles https://github.com/brianmario/mysql2/issues/896, where the author didn't report a reason, but reported a similar workaround to the above.

The second problem resembles https://github.com/brianmario/mysql2/issues/956, although that issue is closed with the release 0.5.1. We currently use 0.5.2.

I suspect the root cause of this issue is somewhere inside mysql2, but I don't know what. The connection are not being shared across multiple threads, so this shouldn't be an issue. We are writing to the database as fast as we can in a loop, perhaps this contributes to the problem as slowing it down with a new connection every loop seems to have helped.

**Comment by shuhaowu** [comment]
Worked around in 56a3100b12ecf7c09f4fc7a4fbda93325d147efb

**Comment by fw42** [comment]
Looks related/identical to https://github.com/brianmario/mysql2/issues/1043.
