### ISSUE TITLE
failed to read current binlog position 

### ISSUE THREAD

**Issue by ridvankaratas** [Shopify/ghostferry#92]
Hello,

I have an old MariaDB server and I wanted to use this tool for migration. Source MariaDB server was 10.0.x and binlog_row_image was not supported in this version. That's why I've upgraded it to 10.2.22 and this variable is working fine. 

After granting necessary permissions to the migration user for both source and target servers, I got this error: 

```
ERRO[0000] failed to read current binlog position        error="sql: expected 4 destination arguments in Scan, not 5" tag=binlog_streamer
error: failed to start ferry: sql: expected 4 destination arguments in Scan, not 5
```

I checked your binary codes and did so for the tutorial, but I couldn't find where exactly is locating for binlog position. 

Can you please advise how to fix it?

Thanks in advance.

**Comment by shuhaowu** [comment]
Can you post the output of `SHOW MASTER STATUS` from your database? The code that's giving the error is here: https://github.com/Shopify/ghostferry/blob/908c310e1f4ea079c77c62090a12872e2721fb6f/utils.go#L146
