### ISSUE TITLE
Foreign key constraint is incorrectly formed

### ISSUE THREAD

**Issue by ridvankaratas** [Shopify/ghostferry#95]
When it comes to creating a table on the target server with Foreign Key and if referenced table hasn't created yet, it gives an error.

`cannot create table, this may leave the target database in an insane state  error="Error 1005: Can't 
create table publisher.View (errno: 150 \"Foreign key constraint is incorrectly formed\")" 
table=publisher.View error: failed to create databases and tables: Error 1005: Can't create table 
publisher.View (errno: 150 "Foreign key constraint is incorrectly formed")`

Example of a create Query for View Table:

> CREATE TABLE `View` (
>   `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
>   `platform_id` int(10) unsigned NOT NULL,
>   `user_id` int(11) NOT NULL,
>   `object_id` int(10) unsigned NOT NULL,
>   `object_type` tinyint(4) NOT NULL,
>   `timestamp` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
>   PRIMARY KEY (`id`),
>   KEY `view_platform_id_foreign` (`platform_id`),
>   CONSTRAINT `view_platform_id_foreign` FOREIGN KEY (`platform_id`) REFERENCES `Platform` (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

In this case, `ghostfrerry-copydb` hasn't created `Platform` table yet. 

We have a fix for this too. Just putting this issue here for future reference.

**Comment by shuhaowu** [comment]
We don't support foreign keys in Ghostferry. It would be difficult to add this feature in correctly. See #3 and https://github.com/github/gh-ost/issues/507

**Comment by shuhaowu** [comment]
As of now, we do not plan on adding this feature into Ghostferry due to cost and complexity.

See also: #3

**Comment by shuhaowu** [comment]
See #166
